name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Mesa
        run: | 
          sudo apt update
          sudo wget https://github.com/mmatl/travis_debs/raw/master/xenial/mesa_18.3.3-0.deb
          sudo dpkg -i ./mesa_18.3.3-0.deb || true
          sudo apt install -f
      - name: Setup cadquery
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cadquery
          environment-file: ./environments/cadquery.yml
          python-version: 3.10.4
      - name: Run cadquery
        shell: bash -l {0}
        run: |
          conda info
          conda list
          mkdir outputs
          python build.py
      - name: Setup Renderer
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: renderer
          environment-file: ./environments/renderer.yml
          python-version: 3.6.15
      - name: Run Renderer
        shell: bash -l {0}
        run: |
          conda info
          conda list
          git clone https://github.com/mmatl/pyopengl.git
          pip install ./pyopengl
          python render.py
      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/