name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: cadquery
          environment-file: environment.yml
          python-version: 3.10.4
      - shell: bash -l {0}
        run: |
          conda info
          conda list