name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cadquery
          environment-file: environment.yml
          python-version: 3.10.4
      - name: Run
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python build.py